#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["fonttools==4.65.0", "brotli==1.2.0", "cairosvg==2.9.1"]
# ///
"""Generate the shared Verimots lettering and icons: uv run this file.

The icon V is an outline of the same glyph shipped in the web/native tile
font. All raster, adaptive and web icons therefore have one source.
"""
from io import BytesIO
from pathlib import Path

import cairosvg
from fontTools import subset
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "assets/verimots"
WEB = ROOT / "web"
LANDING = ROOT / "landing"
ANDROID = ROOT / "android/app/src/main"


def write(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content if isinstance(content, bytes) else content.encode())


# Keep the original font untouched. Rename the subset because Liberation is
# a Reserved Font Name under its OFL license; outlines remain unmodified.
font = TTFont(SOURCE / "LiberationSans-Regular.ttf", recalcTimestamp=False)
options = subset.Options()
options.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14, 16, 17]
options.name_legacy = True
options.name_languages = [0x409]
options.drop_tables += ["FFTM"]
subsetter = subset.Subsetter(options=options)
subsetter.populate(unicodes=[*range(0x20, 0x180), 0x2019])
subsetter.subset(font)
names = {1: "Verimots Tiles", 2: "Regular", 3: "Verimots Tiles Regular 1.0",
         4: "Verimots Tiles Regular", 6: "VerimotsTiles-Regular",
         16: "Verimots Tiles", 17: "Regular"}
for record in font["name"].names:
    if record.nameID in names:
        record.string = names[record.nameID].encode(record.getEncoding())
for name_id, value in names.items():
    font["name"].setName(value, name_id, 3, 1, 0x409)

ttf = BytesIO()
font.save(ttf)
write(ANDROID / "res/font/verimots_tiles.ttf", ttf.getvalue())
font.flavor = "woff2"
woff = BytesIO()
font.save(woff)
for site in (WEB, LANDING):
    write(site / "fonts/verimots-tiles.woff2", woff.getvalue())
    write(site / "fonts/OFL.txt", (SOURCE / "OFL.txt").read_bytes())
write(ANDROID / "assets/fonts/OFL.txt", (SOURCE / "OFL.txt").read_bytes())

glyphs = font.getGlyphSet()
v = glyphs[font.getBestCmap()[ord("V")]]
bounds = BoundsPen(glyphs)
v.draw(bounds)
xmin, ymin, xmax, ymax = bounds.bounds
scale = 23 / (ymax - ymin)
pen = SVGPathPen(glyphs, ntos=lambda n: f"{n:.4f}".rstrip("0").rstrip("."))
v.draw(TransformPen(pen, (scale, 0, 0, -scale,
                          32 - (xmin + xmax) * scale / 2, 41 + ymin * scale)))
v_path = pen.getCommands()

tile_shadow = "M21,14H43Q52,14 52,23V45Q52,54 43,54H21Q12,54 12,45V23Q12,14 21,14Z"
tile_face = "M21,10H43Q52,10 52,19V41Q52,50 43,50H21Q12,50 12,41V19Q12,10 21,10Z"
tile_light = "M21,12H43Q50,12 50,19V39Q50,46 43,46H21Q14,46 14,39V19Q14,12 21,12Z"
disc = "M48,38a10,10 0,1 0,0 20a10,10 0,1 0,0 -20"
check = "M44,48l3,3l5,-6"

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <!-- Generated by scripts/build-verimots-brand.py. -->
  <rect width="64" height="64" rx="14" fill="#142018"/>
  <path d="{tile_shadow}" fill="#a3853f"/>
  <path d="{tile_face}" fill="#f3e5c2"/>
  <path d="{tile_light}" fill="#fff3d1"/>
  <path d="{v_path}" fill="#1c241a"/>
  <path d="{disc}" fill="#3dce8a" stroke="#142018" stroke-width="3"/>
  <path d="{check}" fill="none" stroke="#142018" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
'''
for site in (WEB, LANDING):
    write(site / "favicon.svg", svg)
rasters = [(WEB / "icon-192.png", 192), (WEB / "icon-512.png", 512),
           (WEB / "apple-touch-icon.png", 180), (LANDING / "icon.png", 192)]
for density, size in (("mdpi", 48), ("hdpi", 72), ("xhdpi", 96),
                      ("xxhdpi", 144), ("xxxhdpi", 192)):
    rasters.append((ANDROID / f"res/mipmap-{density}/ic_launcher.png", size))
for path, size in rasters:
    write(path, cairosvg.svg2png(bytestring=svg.encode(), output_width=size, output_height=size))

vector_head = '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/build-verimots-brand.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">
    <group android:scaleX="1.15" android:scaleY="1.15" android:translateX="15" android:translateY="15">
'''
foreground = vector_head + f'''
        <path android:fillColor="#a3853f" android:pathData="{tile_shadow}" />
        <path android:fillColor="#f3e5c2" android:pathData="{tile_face}" />
        <path android:fillColor="#fff3d1" android:pathData="{tile_light}" />
        <path android:fillColor="#1c241a" android:pathData="{v_path}" />
        <path android:fillColor="#3dce8a" android:strokeColor="#142018" android:strokeWidth="3" android:pathData="{disc}" />
        <path android:fillColor="@android:color/transparent" android:strokeColor="#142018" android:strokeWidth="2.5"
            android:strokeLineCap="round" android:strokeLineJoin="round" android:pathData="{check}" />
    </group>
</vector>
'''
write(ANDROID / "res/drawable/ic_launcher_fg.xml", foreground)
mono = vector_head + f'''
        <path android:fillColor="@android:color/transparent" android:strokeColor="#ffffff" android:strokeWidth="3"
            android:strokeLineJoin="round" android:pathData="M36,50H21Q12,50 12,41V19Q12,10 21,10H43Q52,10 52,19V32" />
        <path android:fillColor="#ffffff" android:pathData="{v_path}" />
        <path android:fillColor="@android:color/transparent" android:strokeColor="#ffffff" android:strokeWidth="2.5" android:pathData="{disc}" />
        <path android:fillColor="@android:color/transparent" android:strokeColor="#ffffff" android:strokeWidth="2.5"
            android:strokeLineCap="round" android:strokeLineJoin="round" android:pathData="{check}" />
    </group>
</vector>
'''
write(ANDROID / "res/drawable/ic_launcher_mono.xml", mono)
print("Generated shared Verimots web, landing and Android lettering/icons.")
